version: "3"

services:

  db:
    image: "postgres:11-alpine"
    restart: always
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
        - db:postgresql.local
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=webapp.settings.local
    command: tail -f /dev/null
    volumes:
        - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=webapp.settings.local
    command: sh ./scripts/run_celery.sh
    # user: $UID:$GID
    volumes:
      - .:/webapp
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=webapp.settings.local
    command: sh ./scripts/run_celery_beat.sh
    volumes:
      - .:/webapp
    depends_on:
      - redis

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - "127.0.0.1:8888:8888"
    depends_on:
      - redis